# Generated by Django 2.1.1 on 2018-10-18 18:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FileRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('file_name', models.CharField(blank=True, default='', max_length=200)),
                ('parent', models.CharField(default='', max_length=200)),
                ('file_data', models.BinaryField()),
                ('md5sum', models.CharField(default='', max_length=40)),
                ('file_type', models.CharField(default='txt', max_length=20)),
                ('file_or_not', models.BooleanField(default=1)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('created',),
            },
        ),
    ]
