# Generated by Django 2.1.1 on 2018-10-18 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedatabase', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='filerecord',
            name='file_or_not',
        ),
        migrations.AlterField(
            model_name='filerecord',
            name='parent',
            field=models.CharField(default='NULL', max_length=200),
        ),
    ]
