# Generated by Django 2.1.1 on 2018-10-22 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedatabase', '0004_auto_20181022_1020'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerecord',
            name='file_data',
            field=models.BinaryField(default='', max_length=8000),
        ),
    ]
