# Generated by Django 2.1.1 on 2018-10-22 07:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedatabase', '0006_auto_20181022_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerecord',
            name='file_data',
            field=models.BinaryField(default='', editable=True),
        ),
    ]
