# Generated by Django 2.1.1 on 2018-10-22 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedatabase', '0007_auto_20181022_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerecord',
            name='file_data',
            field=models.BinaryField(default=b'', editable=True),
        ),
        migrations.AlterField(
            model_name='filerecord',
            name='path',
            field=models.CharField(default='', max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='filerecord',
            unique_together={('file_name', 'parent_path')},
        ),
    ]
