# Generated by Django 2.1.1 on 2018-10-22 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedatabase', '0008_auto_20181022_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerecord',
            name='file_type',
            field=models.CharField(default='', max_length=20),
        ),
    ]
