# Generated by Django 2.1.1 on 2018-10-23 04:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedatabase', '0009_auto_20181022_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerecord',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=200, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='filerecord',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='filerecord',
            name='parent_path',
        ),
        migrations.RemoveField(
            model_name='filerecord',
            name='path',
        ),
    ]
