# Generated by Django 2.1.1 on 2018-10-23 18:27

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('filedatabase', '0010_auto_20181023_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerecord',
            name='file_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AlterUniqueTogether(
            name='filerecord',
            unique_together={('owner', 'file_name')},
        ),
    ]
