# Generated by Django 2.1.1 on 2018-10-23 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedatabase', '0011_auto_20181023_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerecord',
            name='file_type',
            field=models.CharField(default='', max_length=200),
        ),
    ]
