# Generated by Django 2.1.1 on 2018-10-24 15:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('filedatabase', '0012_auto_20181024_0255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='filerecord',
            name='file_data',
            field=models.TextField(default=''),
        ),
    ]
